name: Shopee Automation

on:
  schedule:
    - cron: '*/30 * * * *'  # Roda todos os dias às 07h da manhã (Horário de Brasília)
  workflow_dispatch:  # Permite rodar manualmente também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium

    - name: Criar hxh.json com segredo
      run: |
        echo "${{ secrets.HXH_JSON }}" > hxh.json

    - name: Executar o script
      run: python main.py
