name: Shopee Automation

on:
  schedule:
    - cron: '*/30 * * * *'  # Executa a cada 30 minutos
  workflow_dispatch:        # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium

    - name: Criar hxh.json com segredo
      run: |
        mkdir -p /app
        echo "${{ secrets.HXH_JSON }}" > /app/hxh.json

    - name: Executar o script
      run: python main.py
      env:
        PYPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
        PLAYWRIGHT_BROWSERS_PATH: 0
